name: Release Alt

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  lint_javascript:
    name: "📝 Lint: JavaScript"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { cache: yarn, node-version: "${{ matrix.node }}" }
      - run: yarn install --frozen-lockfile
      - run: npx eslint .
      - run: npx prettier "./packages/*/*/{src,bin,test}/**/*.{js,json,md}" --list-different

  lint_rust:
    name: "📝 Lint: Rust"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rust-toolchain
        with: { components: "clippy, rustfmt" }
      - uses: Swatinem/rust-cache@v2
        with: { shared-key: "${{ matrix.os }}" }
      - run: cargo fmt --all -- --check
      - run: cargo clippy -- -D warnings

  build_javascript:
    name: "🔨 JavaScript"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { cache: yarn, node-version: "${{ matrix.node }}" }
      - uses: ./.github/actions/rust-toolchain
      - uses: Swatinem/rust-cache@v2
        with: { shared-key: "${{ matrix.os }}" }
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn build-ts
      - uses: actions/upload-artifact@v4
        with:
          name: packages-javascript
          path: ${{ github.workspace }}/packages/**/*
          if-no-files-found: error
          retention-days: 1

  build_native:
    strategy:
      matrix:
        config:
          - name: "🔨🐥 Linux AMD64"
            runner: ubuntu-24.04
            RUSTUP_TARGET: x86_64-unknown-linux-gnu
          - name: "🔨🐥 Linux ARM64"
            runner: ubuntu-24.04-arm
            RUSTUP_TARGET: aarch64-unknown-linux-gnu
          - name: "🔨🍎 MacOS ARM64"
            runner: macos-15
            RUSTUP_TARGET: aarch64-apple-darwin
          - name: "🔨🍎 MacOS AMD64"
            runner: macos-15
            RUSTUP_TARGET: x86_64-apple-darwin
    name: "${{ matrix.config.name }}"
    runs-on: ${{ matrix.config.runner }}
    env:
      RUSTUP_TARGET: ${{ matrix.config.RUSTUP_TARGET }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { cache: yarn, node-version: "${{ matrix.node }}" }
      - uses: ./.github/actions/rust-toolchain
      - uses: Swatinem/rust-cache@v2
        with: { shared-key: "${{ matrix.os }}" }
      - run: rustup target add ${{ matrix.config.RUSTUP_TARGET }}
      - run: yarn install --frozen-lockfile
      - run: yarn build-native-release
      - uses: actions/upload-artifact@v4
        with:
          name: "packages-${{ matrix.config.RUSTUP_TARGET }}"
          path: ${{ github.workspace }}/packages/**/*
          if-no-files-found: error
          retention-days: 1

  integration_tests:
    strategy:
      matrix:
        config:
          - name: "🧪🐥 Linux AMD64"
            runner: ubuntu-24.04
          - name: "🧪🍎 MacOS ARM64"
            runner: macos-15
    name: "${{ matrix.config.name }}"
    runs-on: ${{ matrix.config.runner }}
    timeout-minutes: 35
    needs:
      - build_native
      - build_javascript
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { cache: yarn, node-version: "${{ matrix.node }}" }
      - uses: ./.github/actions/rust-toolchain
      - uses: Swatinem/rust-cache@v2
        with: { shared-key: "${{ matrix.os }}" }
      - uses: actions/download-artifact@v4
        with:
          pattern: packages-*
          path: packages
          merge-multiple: true
      - run: yarn install --frozen-lockfile
      - run: yarn test:integration

  integration_tests_v3:
    strategy:
      matrix:
        config:
          - name: "🧪🐥 Linux AMD64"
            runner: ubuntu-24.04
          - name: "🧪🍎 MacOS ARM64"
            runner: macos-15
    name: "${{ matrix.config.name }}"
    runs-on: ${{ matrix.config.runner }}
    timeout-minutes: 35
    needs:
      - build_native
      - build_javascript
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { cache: yarn, node-version: "${{ matrix.node }}" }
      - uses: ./.github/actions/rust-toolchain
      - uses: Swatinem/rust-cache@v2
        with: { shared-key: "${{ matrix.os }}" }
      - uses: actions/download-artifact@v4
        with:
          pattern: packages-*
          path: packages
          merge-multiple: true
      - run: yarn install --frozen-lockfile
      - run: yarn test:integration:v3

  e2e_tests:
    strategy:
      matrix:
        config:
          - name: "🧪🐥 Linux AMD64"
            runner: ubuntu-24.04
          - name: "🧪🍎 MacOS ARM64"
            runner: macos-15
    name: "${{ matrix.config.name }}"
    runs-on: ${{ matrix.config.runner }}
    timeout-minutes: 35
    needs:
      - build_native
      - build_javascript
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { cache: yarn, node-version: "${{ matrix.node }}" }
      - uses: ./.github/actions/rust-toolchain
      - uses: Swatinem/rust-cache@v2
        with: { shared-key: "${{ matrix.os }}" }
      - uses: actions/download-artifact@v4
        with:
          pattern: packages-*
          path: packages
          merge-multiple: true
      - name: Bump max inotify watches (Linux only)
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p;
        if: ${{ runner.os == 'Linux' }}
      - run: yarn install --frozen-lockfile
      - run: yarn playwright install
      - run: yarn test:e2e:ci

  unit_tests_javascript:
    name: "🔬 Unit Tests: JavaScript"
    runs-on: ubuntu-24.04
    needs:
      - build_native
      - build_javascript
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { cache: yarn, node-version: "${{ matrix.node }}" }
      - uses: actions/download-artifact@v4
        with:
          pattern: packages-*
          path: packages
          merge-multiple: true
      - run: yarn install --frozen-lockfile
      - run: yarn test:js:unit

  unit_tests_rust:
    name: "🔬 Unit Tests: Rust"
    runs-on: ubuntu-24.04
    needs:
      - build_native
      - build_javascript
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { cache: yarn, node-version: "${{ matrix.node }}" }
      - run: cargo test

  publish_npm:
    name: "🔄 Publish: NPM Packages"
    runs-on: ubuntu-24.04
    needs:
      - lint_javascript
      - lint_rust
      - build_javascript
      - build_native
      - integration_tests
      - integration_tests_v3
      - e2e_tests
      - unit_tests_javascript
      - unit_tests_rust
    steps:
      - run: echo "Made it"

  publish_github_release:
    name: "🔄 Publish: Github Release"
    runs-on: ubuntu-24.04
    needs:
      - lint_javascript
      - lint_rust
      - build_javascript
      - build_native
      - integration_tests
      - integration_tests_v3
      - e2e_tests
      - unit_tests_javascript
      - unit_tests_rust
    steps:
      - run: echo "Made it"
